services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: money-tracker-app
    ports:
      - "${APP_PORT:-8000}:8000"
      - "${VITE_PORT:-5173}:5173"
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    environment:
      APP_URL: "${APP_URL:-http://localhost:8000}"
