/**
 * Mapa de iconos permitidos para categorías de gasto (Lucide).
 * Debe coincidir con config/expense_category_icons.php.
 */
import * as React from 'react';
import type { LucideIcon } from 'lucide-react';
import {
    Wallet,
    ShoppingCart,
    ShoppingBag,
    Tag,
    Utensils,
    UtensilsCrossed,
    Coffee,
    CupSoda,
    Wine,
    Car,
    Bus,
    Train,
    Plane,
    PlaneTakeoff,
    Bike,
    Home,
    Building2,
    Briefcase,
    Heart,
    HeartPulse,
    Stethoscope,
    Pill,
    Dumbbell,
    Shirt,
    Smartphone,
    Laptop,
    Tv,
    Gamepad2,
    Music,
    Headphones,
    Film,
    BookOpen,
    Book,
    GraduationCap,
    Baby,
    Dog,
    Cat,
    Gift,
    Cake,
    Croissant,
    Apple,
    Fish,
    Milk,
    MapPin,
    Landmark,
    Hotel,
    Store,
    Sofa,
    Banknote,
    Coins,
    PiggyBank,
    CreditCard,
    TrendingUp,
    Receipt,
    Package,
    Truck,
    Fuel,
    Zap,
    Droplets,
    Leaf,
    Sun,
    Moon,
    Cloud,
    Umbrella,
    Wrench,
    Hammer,
    Paintbrush,
    TreePine,
    Flower2,
    ClipboardList,
    Calendar,
    CalendarDays,
    Clock,
    Star,
    Flame,
    Lightbulb,
    BarChart3,
    PieChart,
    Activity,
    Sparkles,
    Beef,
    CircleParking,
    Cookie,
    GlassWater,
    Hospital,
    IceCream,
    PartyPopper,
    PawPrint,
    Pizza,
    Plug,
    Repeat,
    Rss,
    Salad,
    Sandwich,
    Scissors,
    Soup,
    Syringe,
    Ticket,
    WashingMachine,
    Wifi,
    Key,
    ShoppingBasket,
    Euro,
    DollarSign,
    AlertCircle,
    Info,
    CircleHelp,
} from 'lucide-react';

const iconEntries = [
    ['Wallet', Wallet],
    ['ShoppingCart', ShoppingCart],
    ['ShoppingBag', ShoppingBag],
    ['Tag', Tag],
    ['Utensils', Utensils],
    ['UtensilsCrossed', UtensilsCrossed],
    ['Coffee', Coffee],
    ['CupSoda', CupSoda],
    ['Wine', Wine],
    ['Car', Car],
    ['Bus', Bus],
    ['Train', Train],
    ['Plane', Plane],
    ['PlaneTakeoff', PlaneTakeoff],
    ['Bike', Bike],
    ['Home', Home],
    ['Building2', Building2],
    ['Briefcase', Briefcase],
    ['Heart', Heart],
    ['HeartPulse', HeartPulse],
    ['Stethoscope', Stethoscope],
    ['Pill', Pill],
    ['Dumbbell', Dumbbell],
    ['Shirt', Shirt],
    ['Smartphone', Smartphone],
    ['Laptop', Laptop],
    ['Tv', Tv],
    ['Gamepad2', Gamepad2],
    ['Music', Music],
    ['Headphones', Headphones],
    ['Film', Film],
    ['BookOpen', BookOpen],
    ['Book', Book],
    ['GraduationCap', GraduationCap],
    ['Baby', Baby],
    ['Dog', Dog],
    ['Cat', Cat],
    ['Gift', Gift],
    ['Cake', Cake],
    ['Croissant', Croissant],
    ['Apple', Apple],
    ['Fish', Fish],
    ['Milk', Milk],
    ['MapPin', MapPin],
    ['Landmark', Landmark],
    ['Hotel', Hotel],
    ['Store', Store],
    ['Sofa', Sofa],
    ['Banknote', Banknote],
    ['Coins', Coins],
    ['PiggyBank', PiggyBank],
    ['CreditCard', CreditCard],
    ['TrendingUp', TrendingUp],
    ['Receipt', Receipt],
    ['Package', Package],
    ['Truck', Truck],
    ['Fuel', Fuel],
    ['Zap', Zap],
    ['Droplets', Droplets],
    ['Leaf', Leaf],
    ['Sun', Sun],
    ['Moon', Moon],
    ['Cloud', Cloud],
    ['Umbrella', Umbrella],
    ['Wrench', Wrench],
    ['Hammer', Hammer],
    ['Paintbrush', Paintbrush],
    ['TreePine', TreePine],
    ['Flower2', Flower2],
    ['ClipboardList', ClipboardList],
    ['Calendar', Calendar],
    ['CalendarDays', CalendarDays],
    ['Clock', Clock],
    ['Star', Star],
    ['Flame', Flame],
    ['Lightbulb', Lightbulb],
    ['BarChart3', BarChart3],
    ['PieChart', PieChart],
    ['Activity', Activity],
    ['Sparkles', Sparkles],
    ['Beef', Beef],
    ['CircleParking', CircleParking],
    ['Cookie', Cookie],
    ['GlassWater', GlassWater],
    ['Hospital', Hospital],
    ['IceCream', IceCream],
    ['PartyPopper', PartyPopper],
    ['PawPrint', PawPrint],
    ['Pizza', Pizza],
    ['Plug', Plug],
    ['Repeat', Repeat],
    ['Rss', Rss],
    ['Salad', Salad],
    ['Sandwich', Sandwich],
    ['Scissors', Scissors],
    ['Soup', Soup],
    ['Syringe', Syringe],
    ['Ticket', Ticket],
    ['WashingMachine', WashingMachine],
    ['Wifi', Wifi],
    ['Key', Key],
    ['ShoppingBasket', ShoppingBasket],
    ['Euro', Euro],
    ['DollarSign', DollarSign],
    ['AlertCircle', AlertCircle],
    ['Info', Info],
    ['CircleHelp', CircleHelp],
] as const satisfies ReadonlyArray<readonly [string, LucideIcon]>;

export const EXPENSE_CATEGORY_ICON_MAP: Record<string, LucideIcon> = Object.fromEntries(iconEntries);

export function ExpenseCategoryIcon({
    name,
    className,
}: {
    name: string | null | undefined;
    className?: string;
}): React.ReactElement {
    const Icon = (name !== null && name !== undefined && EXPENSE_CATEGORY_ICON_MAP[name] !== undefined)
        ? EXPENSE_CATEGORY_ICON_MAP[name]
        : Tag;

    return <Icon className={className} aria-hidden />;
}
